#production:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: p765r391_bAvy
#  pool: 5
#  username: p765r391
#  password: pAwYX4gr
#  socket: /tmp/mysql.sock


production:
  adapter: sqlite3
#  encoding: utf8
#  reconnect: false
  database: db/db_production
  timeout: 5000
#  pool: 5
#  username: p765r391
#  password: pAwYX4gr
#  socket: /tmp/mysql.sock

